import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { DataTable } from '@/components/ui/data-table'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { Download } from 'lucide-react'
import type { Database } from '@/types/supabase-types'
import type { TableRow } from '@/types/table'

type Report = Database['public']['Tables']['reports']['Row'] & {
  generated_by: Database['public']['Tables']['members']['Row']
}

const columns = [
  {
    accessorKey: 'name',
    header: 'Report Name',
  },
  {
    accessorKey: 'type',
    header: 'Type',
  },
  {
    accessorKey: 'created_at',
    header: 'Generated',
    cell: ({ row }: { row: TableRow<Report> }) => {
      return new Date(row.getValue('created_at')).toLocaleString()
    },
  },
  {
    accessorKey: 'generated_by.email',
    header: 'Generated By',
    cell: ({ row }: { row: TableRow<Report> }) => {
      return row.original.generated_by?.email || 'N/A'
    },
  },
  {
    id: 'actions',
    cell: ({ row }: { row: TableRow<Report> }) => {
      return (
        <div className="flex gap-2">
          <Button variant="ghost" size="sm">
            <Download className="h-4 w-4 mr-1" />
            Download
          </Button>
          <Link href={`/admin/reports/${row.original.id}`}>
            <Button variant="ghost" size="sm">
              View
            </Button>
          </Link>
        </div>
      )
    },
  },
]

export default async function ReportsPage() {
  const supabase = createServerComponentClient<Database>({ cookies })
  
  const { data: reports } = await supabase
    .from('reports')
    .select('*, generated_by:members(*)')
    .order('created_at', { ascending: false })

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold">Reports</h1>
        <Link href="/admin/reports/generate">
          <Button>Generate Report</Button>
        </Link>
      </div>
      
      <DataTable
        columns={columns}
        data={(reports as unknown as Report[]) || []}
        searchKey="name"
      />
    </div>
  )
} 